### ISSUE TITLE
Validation error when updating plugin

### ISSUE THREAD

**Issue by ecottis** [StudiUM/moodle-report_lpmonitoring#12]
Unfortunately there seems to be  a validation error when installing this latest update.  

Can you please review 

Thanks

**Comment by levemar** [comment]
Hi @ecottis,
Sorry to hear that. Can you give us a little bit more information?

- What is your moodle version?
- What is the error message you receive and where? (a screenshot might also help)

Thanks,
Marie-Eve

**Comment by leblangi** [comment]
Hello, due to the lack of information related to this problem, I am closing the ticket. Please reopen another one if the problem persists, adding as much detail as possible in order to be able to reproduce the problem.
