### ISSUE TITLE
M4.1 / Php 8.1 | systemrol don't see the menu links

### ISSUE THREAD

**Issue by gemguardian** [StudiUM/moodle-report_lpmonitoring#16]
As a siteadmin I see at **siteadmin**>**Reports**>**Monitoring of learning plans** and **Statistics for learning plans**
I can also see at **siteadmin**>**competencies**>**Competencies scale colours**

Though the systemrol **manager** cannot see the links in the menu. 
We are using M4.1, PHP 8.1, Boost 

I noticed is has been reported before https://github.com/StudiUM/moodle-report_lpmonitoring/issues/1 but closed. 

If I give the links to the pages, they do have the premissions but they cannot find it in the menu's. 
it would be great if this could be resolved. 

Thank you :)

**Comment by leblangi** [comment]
Hello @gemguardian,

It is a regression you have with PHP 8.1 or it never worked ?

Normally, you have to create new category role for allow user to see the asked information. See documentation, section "Role and permissions" :
https://moodle.org/plugins/report_lpmonitoring

**Comment by gemguardian** [comment]
@leblangi I have  never tried the module before PHP 8.1 so I am not sure if it a regression. 
But I am guess it never worked ór it broke with the new Boost theme. 

Currently I solved it with a HTML block which contains the links.

**Comment by leblangi** [comment]
@gemguardian, can you try do create the categories roles. We have this role created:

- Study Plan Manager - Administration: This role manages the skills frameworks and study plan models within the faculty/department/school.
- Study Plan Manager - User: This role manages the study plans for an assigned cohort.
- Study plan assessor - Administration: This role consults the skills frameworks and study plan models without being able to modify them.
- Study Plan Reviewer - User: This role views and reviews study plans for an assigned cohort.

I just tested with an user with "Study Plan Manager - Administration" and he is able to see the report but the link to it is available from the menu in the category page. Can you try this ? Thanks !

**Comment by gemguardian** [comment]
@leblangi thank you - the client was happy with the current solution. I made a note for next time to try it out.
