### ISSUE TITLE
demande d'ajout de fonctionnalités 

### ISSUE THREAD

**Issue by david-85** [StudiUM/moodle-report_lpmonitoring#4]
Bonjour je me permet de vous écrire pour vous demander de l'aide. je voudrais savoir, est-il possible d'ajouter une fonctionnalité à votre plugging? 

Je rencontre un soucis, lorsque les utilisateurs on réalisés  un test (quiz) mais qu'ils ne l'ont pas complètement fini, si par erreur le test est envoyé, le plugging enregistre la compétence avec une note erroné. 

par la suite si l'on veut supprimer la tentative afin de refaire le quiz, il'n'est pas possible de réinitialiser le plan de formation pour certaine compétence. 
serait il possible d'ajouter un bouton RAZ (remise à zéro) en dessous du bouton Evaluer qui permettrais de remettre la compétence à sont état initiale ( non noté) 

je vous joint une image montrant ce que j'aimerai ajouter 

je vous remercie beaucoup d'avance 

cordialement 
David 
![plan de formation](https://user-images.githubusercontent.com/48823859/54812206-dc7eb500-4c8a-11e9-9287-8d6aabdca92e.png)

**Comment by levemar** [comment]
Bonjour, 

Effectivement cela pourrait être intéressant, toutefois cette demande n'est pas liée directement à notre plugin mais plutôt aux fonctionnalités "core" de Moodle. Notre lpmonitoring ne sert qu'à collecter de l'information un peu partout et l'afficher de façon plus conviviale, mais on se base toujours sur les données sauvegardées par les fonctionnalités core. Il n'est pas possible actuellement de réinitialiser une compétence dans les interfaces "core" liées aux compétences. 

Par interface core je veux dire par exemple sur la page du "Plan d'étude" d'un étudiant et non pas dans "Suivi des plans d'études". Je pense que cette fonctionnalité devrait logiquement être ajoutée dans le popup d'évaluation (voir ci-dessous). Il est utilisé pour tous les niveaux d'évaluation des compétences et comme il est identique dans le core et dans notre plugin alors automatiquement la fonctionnalité deviendrait disponible dans notre plugin.

![image](https://user-images.githubusercontent.com/48833668/54834606-e0183900-4c96-11e9-9e1d-cdc8ca1a180b.png)

Je vous invite à en discuter directement dans les forums ou le tracker de Moodle.

Dans tous les cas, si cette fonctionnalité est ajoutée d'une façon ou d'une autre dans le core, alors nous serons en mesure d'ajouter un bouton ou un lien quelconque pour l'utiliser. 

On va tout de même regarder plus en détails de notre côté, mais à priori il y aura beaucoup d'implication un peu partout alors ça ne serait pas simple à ajouter du côté de lpmonitoring seulement.

Bonne journée,
Marie-Eve

**Comment by david-85** [comment]
Bonjour et Merci Marie-Eve, j'ai aussitôt poster votre réponse sur le forum d'aide Moodle afin de solliciter les Moodleur mais sans réponse. Cette Fonctionnalité serait pourtant vraiment utile. Avez vous fait des recherche de votre coté depuis votre réponse ? 

je vous remercie d'avance 

cordialement 
Bonne journée
David

**Comment by levemar** [comment]
J'ai vu vos demandes dans le forum francophone et en commentaire sur une demande du tracker. Idéalement il faut ouvrir une nouvelle demande dans le tracker mais effectivement ce n'est pas toujours facile. Il faut la documenter le plus possible. Si vous mettez des captures d'écran, assurez vous de prendre les interfaces natives de moodle et non pas notre plugin. Le visuel pour notre plugin pourrait être corrigé plus tard, si la fonctionnalité est ajoutée au core. 
Si vous parlez anglais, vous pouvez aussi poser la question sur le forum qui parle spécifiquement des compétences, peut-être aurez vous plus de succès que sur le forum francophone : https://moodle.org/mod/forum/view.php?id=8266 

Cordialement,
Marie-Eve

**Comment by levemar** [comment]
Bonjour David, 
Je ne sais pas si vous avez trouvé une autre solution entre temps, mais notre nouvelle version de lpmonitoring, publiée hier, inclus justement cette fonctionnalité de réinitialiser les évaluations des compétences (une compétence à la fois ou toutes les compétences d'un plan d'études en même temps).
Bonne journée, 
Marie-Eve

**Comment by LoLau13** [comment]
Bonjour,
Je vous contacte pour avoir un peu d'aide car je bloque actuellement sur un sujet.
Je n'arrive pas à comprendre la différence entre l'évaluation de cours et l'évaluation finale dans le suivi des plans d'études.

D'autre part, existe-t-il un formulaire d'accès à l'historique des évaluations finales comme c'est le cas pour les évaluations de cours ?

Je vous remercie par avance pour votre aide ;-)
Laurent

**Comment by levemar** [comment]
Bonjour Laurent, 

Pour la première question, en fait ça dépend de comment vos compétences sont configurées. Dans la page des compétences d'un cours, vous avez accès à ces options : 
![image](https://user-images.githubusercontent.com/48833668/80241187-29248480-8631-11ea-9320-5e88af608411.png)
Si vous avez sélectionné la 2e option, les compétences de vos cours vont généralement être comme l'évaluation finale (surtout si la compétence est associée à un seul cours).
Par contre, si vous choisissez la 1ère, alors les compétences du cours demeurent indépendantes de l'évaluation finale. Vous pouvez par exemple évaluer la même compétence dans 3 cours, puis aller dans le suivi des plans d'études où vous devrez manuellement faire l'évaluation finale.
Est-ce que ça clarifie un peu les choses?

Pour la seconde question, en fait quand vous cliquez sur le titre d'une compétence, dans le Rapport de Suivi des plans d'études, vous avez toute l'historique des preuves. Cela inclus à la fois les évaluations faites dans les cours et les évaluations finales faites au niveau du plan d'études : 
![image](https://user-images.githubusercontent.com/48833668/80241709-10689e80-8632-11ea-9dd6-2e3bed1774cc.png)

Si vous avez d'autres questions, n'hésitez pas!
Marie-Eve

**Comment by LoLau13** [comment]
Bonjour Marie-Ève et merci pour ces précisions très claires.

Bonne continuation et bon courage pour la fin du confinement

Laurent

Envoyé par myMail pour iOS

vendredi 24 avril 2020 à 19:48 +0200 de notifications@github.com <notifications@github.com>:
