### ISSUE TITLE
1.3 Version

### ISSUE THREAD

**Issue by upats** [StudiUM/moodle-report_lpmonitoring#5]
Hello, I am wondering is the 1.3 version that is listed on the Moodle.org plugins repository going to make it's way to Git soon? Or am I just missing where it is? Thank you!

**Comment by taboubi** [comment]
Hi,
It's the tag v1.3 : https://github.com/StudiUM/moodle-report_lpmonitoring/tree/v1.3

**Comment by upats** [comment]
Thank you Issim for taking the time to respond. I am pretty new to Git and missed the tags. I see when I pull master I get the correct version. Cheers.
