### ISSUE TITLE
Coding error detected when viewing an individuals report tab

### ISSUE THREAD

**Issue by betta7776** [StudiUM/moodle-report_lpmonitoring#6]
Hey, 
I am getting the error : Coding error detected, it must be fixed by a programmer: Unexpected property plans

This is happening when I open a learning plan of a specific user, than go over to the "report" tab, and click one of the ratings given by a course.

![Annotation 2019-08-12 084541](https://user-images.githubusercontent.com/41590158/62870054-9203e080-bcde-11e9-882b-41c37c191e39.png)

**Comment by levemar** [comment]
Hi, 
Sorry for the delay, I was on vacations and Issam too (the other maintainer of the plugin).

I will try to look at the problem you encounter with the Report tab as soon as possible, in the next weeks.

Can you provide me as much details as possible? For exemple :
- What version of Moodle do you use?
- What browser do you use?
- Do you have some errors in the javascript console or the php log?
- Are all courses visible to students?
- Is the other tab ("In the details") working correctly?

Thanks!
Marie-Eve

**Comment by levemar** [comment]
Fixed in version v1.4 of the plugin.
