### ISSUE TITLE
Coding error detected, it must be fixed by a programmer: Unexpected property plans.

### ISSUE THREAD

**Issue by calishere** [StudiUM/moodle-report_lpmonitoring#7]
Hi,

Similarly to the user : betta7776 that commented on Aug 12, 2019, i'm, also getting the message "Coding error detected, it must be fixed by a programmer: Unexpected property plans".

File: ...asses/external/exporter.php
Line: 145

Error code: codingerror
* line 145 of /lib/classes/external/exporter.php: coding_exception thrown
* line 74 of /report/lpmonitoring/classes/output/lpmonitoring_user_competency_summary_in_course.php: call to core\external\exporter->export()
* line 1614 of /report/lpmonitoring/classes/external.php: call to report_lpmonitoring\output\lpmonitoring_user_competency_summary_in_course->export_for_template()
* line 244 of /lib/externallib.php: call to report_lpmonitoring\external::data_for_user_competency_summary_in_course()
* line 79 of /lib/ajax/service.php: call to external_api::call_external_function()

I'm running moodle 3.8.1, running on Chrome browser.
"In the details" tab is working fine.
I receive the error message in the "Report" section when i click "Not Rated" inside the table.
![image](https://user-images.githubusercontent.com/57122656/81000918-7e566680-8e79-11ea-9f94-a77cecffc61d.png)

**Comment by levemar** [comment]
Hi, 
I just released a new version of the plugin (v1.4). It should solve this issue and offer a couple of new functionnalities.
Let me know if it works for you.
Marie-Eve
