### ISSUE TITLE
Can it be enlarged?

### ISSUE THREAD

**Issue by dinism** [StudiUM/moodle-report_lpmonitoring#8]
I'm a PT-PT translator.
Thanks for the plugin
Take a look to this:
![imagem](https://user-images.githubusercontent.com/14828021/81485568-cabcf000-9245-11ea-939d-0210afc8628c.png)
![imagem](https://user-images.githubusercontent.com/14828021/81485607-27b8a600-9246-11ea-9aad-2b283b860726.png)

**Comment by dinism** [comment]
First one, yesterday not expanded, today OK
![imagem](https://user-images.githubusercontent.com/14828021/81498679-33e04a00-92be-11ea-8d58-7d46970f899a.png)

**Comment by levemar** [comment]
Hi, 
The size of the final evaluation depends on a lot of factors : the size of the other columns of the report, the size of your screen, etc. This is why sometimes it seems ok and sometimes it is truncated. The first image shows that it could be enlarged a little bit though. I don't think we will work on this really soon but I keep this issue open.

**Comment by leblangi** [comment]
Hello, we are not planning to work on this feature at the moment. So I'm going to close this post. If you are interested in this feature, please provide a pull-request and we will analyze it.
